version: '3'

services:
  mongo:
    image: mongo:4.2
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: sweep
      MONGO_INITDB_ROOT_PASSWORD: sweep

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: sweep
      ME_CONFIG_MONGODB_ADMINPASSWORD: sweep
      ME_CONFIG_MONGODB_URL: mongodb://sweep:sweep@mongo:27017/

#  spring:
#    container_name: jaksim31-backend
#    build:
#      context: ./
#      dockerfile: ./Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mongo
